/**
 * ttsAssets — Hazır (önceden üretilmiş) seslendirme MP3'lerinin slug→modül haritası.
 * ---------------------------------------------------------------------------------
 * BU DOSYA OTOMATİK ÜRETİLİR. Elle düzenleme; şunu çalıştır:
 *   node scripts/gen-tts-assets.mjs
 * (assets/sounds/tts/ altındaki *.mp3 dosyalarını tarar ve aşağıdaki haritayı yazar.)
 *
 * Anahtar (slug) kuralı = services/speechService.ts `ttsSlug()`.
 * speak(text) önce ttsSlug(text) ile buraya bakar; varsa MP3'ü çalar, yoksa sessiz geçer.
 */
export const TTS: Record<string, number> = {
  '1-rakamindan-basla-noktalari-sirayla-birlestir': require('../assets/sounds/tts/1-rakamindan-basla-noktalari-sirayla-birlestir.wav'),
  'aferin-dogru-siraladin': require('../assets/sounds/tts/aferin-dogru-siraladin.wav'),
  'aferin-farkli-olani-buldun': require('../assets/sounds/tts/aferin-farkli-olani-buldun.wav'),
  'aferin-hepsini-siraladin': require('../assets/sounds/tts/aferin-hepsini-siraladin.wav'),
  'aferin-ikizleri-buldun': require('../assets/sounds/tts/aferin-ikizleri-buldun.wav'),
  'aferin-iste-degisen-buydu': require('../assets/sounds/tts/aferin-iste-degisen-buydu.wav'),
  'aferin-tertemiz-oldu': require('../assets/sounds/tts/aferin-tertemiz-oldu.wav'),
  'aferin-tonlari-dogru-siraladin': require('../assets/sounds/tts/aferin-tonlari-dogru-siraladin.wav'),
  'aferin': require('../assets/sounds/tts/aferin.wav'),
  'arkadasimiza-nasil-iyilik-yapariz-bir-daha-bakalim': require('../assets/sounds/tts/arkadasimiza-nasil-iyilik-yapariz-bir-daha-bakalim.wav'),
  'ayni-duyguya-sahip-iki-yuzu-bul': require('../assets/sounds/tts/ayni-duyguya-sahip-iki-yuzu-bul.wav'),
  'ayni-mi-farkli-mi': require('../assets/sounds/tts/ayni-mi-farkli-mi.wav'),
  'bak-cizimin-oynuyor': require('../assets/sounds/tts/bak-cizimin-oynuyor.wav'),
  'birbirinin-aynisi-iki-resmi-bul': require('../assets/sounds/tts/birbirinin-aynisi-iki-resmi-bul.wav'),
  'birbiriyle-giden-ikilileri-eslestir': require('../assets/sounds/tts/birbiriyle-giden-ikilileri-eslestir.wav'),
  'bu-arac-nerede-gider': require('../assets/sounds/tts/bu-arac-nerede-gider.wav'),
  'bu-buyuyunce-ne-olur': require('../assets/sounds/tts/bu-buyuyunce-ne-olur.wav'),
  'bu-canli-mi-cansiz-mi': require('../assets/sounds/tts/bu-canli-mi-cansiz-mi.wav'),
  'bu-esya-hangi-odada-kullanilir': require('../assets/sounds/tts/bu-esya-hangi-odada-kullanilir.wav'),
  'bu-gunduz-mu-gece-mi': require('../assets/sounds/tts/bu-gunduz-mu-gece-mi.wav'),
  'bu-guvenli-degil-kendimizi-nasil-koruruz-bir-daha-bak': require('../assets/sounds/tts/bu-guvenli-degil-kendimizi-nasil-koruruz-bir-daha-bak.wav'),
  'bu-hayvan-ne-yer': require('../assets/sounds/tts/bu-hayvan-ne-yer.wav'),
  'bu-hayvan-nerede-yasar': require('../assets/sounds/tts/bu-hayvan-nerede-yasar.wav'),
  'bu-iki-renk-karisinca-ne-olur': require('../assets/sounds/tts/bu-iki-renk-karisinca-ne-olur.wav'),
  'bu-sicak-mi-soguk-mu': require('../assets/sounds/tts/bu-sicak-mi-soguk-mu.wav'),
  'bu-suya-atilinca-yuzer-mi-batar-mi': require('../assets/sounds/tts/bu-suya-atilinca-yuzer-mi-batar-mi.wav'),
  'bunu-dogru-kutuya-koy': require('../assets/sounds/tts/bunu-dogru-kutuya-koy.wav'),
  'bunu-hangi-kutuya-atariz': require('../assets/sounds/tts/bunu-hangi-kutuya-atariz.wav'),
  'cizimini-kaydettim-aferin': require('../assets/sounds/tts/cizimini-kaydettim-aferin.wav'),
  'cok-guzel-boyadin-aferin': require('../assets/sounds/tts/cok-guzel-boyadin-aferin.wav'),
  'diger-yarisini-da-tamamladin-aferin': require('../assets/sounds/tts/diger-yarisini-da-tamamladin-aferin.wav'),
  'dogru-aferin': require('../assets/sounds/tts/dogru-aferin.wav'),
  'dogru-batiyor': require('../assets/sounds/tts/dogru-batiyor.wav'),
  'dogru-bu-daha-saglikli-aferin': require('../assets/sounds/tts/dogru-bu-daha-saglikli-aferin.wav'),
  'dogru-farklilar': require('../assets/sounds/tts/dogru-farklilar.wav'),
  'dogru-ikisi-de-ayni': require('../assets/sounds/tts/dogru-ikisi-de-ayni.wav'),
  'dogru-iste-buyumus-hali-aferin': require('../assets/sounds/tts/dogru-iste-buyumus-hali-aferin.wav'),
  'dogru-iste-karisim-rengi': require('../assets/sounds/tts/dogru-iste-karisim-rengi.wav'),
  'dogru-oruntuyu-buldun': require('../assets/sounds/tts/dogru-oruntuyu-buldun.wav'),
  'dogru-secim-aferin': require('../assets/sounds/tts/dogru-secim-aferin.wav'),
  'dogru-yuzuyor': require('../assets/sounds/tts/dogru-yuzuyor.wav'),
  'en-acik-tondan-en-koyuya-sirala': require('../assets/sounds/tts/en-acik-tondan-en-koyuya-sirala.wav'),
  'en-agir-olani-bul': require('../assets/sounds/tts/en-agir-olani-bul.wav'),
  'en-azdan-en-coga-dogru-sirala': require('../assets/sounds/tts/en-azdan-en-coga-dogru-sirala.wav'),
  'en-kucuk-ayidan-en-buyuge-dogru-sirala': require('../assets/sounds/tts/en-kucuk-ayidan-en-buyuge-dogru-sirala.wav'),
  'en-uzun-olani-bul': require('../assets/sounds/tts/en-uzun-olani-bul.wav'),
  'evet-bu-daha-agir-aferin': require('../assets/sounds/tts/evet-bu-daha-agir-aferin.wav'),
  'evet-en-uzun-bu-aferin': require('../assets/sounds/tts/evet-en-uzun-bu-aferin.wav'),
  'fareyi-peynire-ulastir-komsu-kareye-dokun': require('../assets/sounds/tts/fareyi-peynire-ulastir-komsu-kareye-dokun.wav'),
  'gunun-sirasini-yap-once-ne-olur-en-bastan-dokun': require('../assets/sounds/tts/gunun-sirasini-yap-once-ne-olur-en-bastan-dokun.wav'),
  'hangi-sayi-daha-buyuk': require('../assets/sounds/tts/hangi-sayi-daha-buyuk.wav'),
  'hangisi-daha-saglikli': require('../assets/sounds/tts/hangisi-daha-saglikli.wav'),
  'hangisi-farkli-otekilere-benzemeyeni-bul': require('../assets/sounds/tts/hangisi-farkli-otekilere-benzemeyeni-bul.wav'),
  'harika-dogru-boyut': require('../assets/sounds/tts/harika-dogru-boyut.wav'),
  'harika-dogru-hatirladin': require('../assets/sounds/tts/harika-dogru-hatirladin.wav'),
  'harika-dogru-sekil': require('../assets/sounds/tts/harika-dogru-sekil.wav'),
  'harika-siraladin-aferin': require('../assets/sounds/tts/harika-siraladin-aferin.wav'),
  'harika-tam-oturdu': require('../assets/sounds/tts/harika-tam-oturdu.wav'),
  'hepsi-kac-etti-say-bakalim': require('../assets/sounds/tts/hepsi-kac-etti-say-bakalim.wav'),
  'iki-tabaga-esit-paylastir-her-tabaga-kac-duser': require('../assets/sounds/tts/iki-tabaga-esit-paylastir-her-tabaga-kac-duser.wav'),
  'iyi-bak-ezberle': require('../assets/sounds/tts/iyi-bak-ezberle.wav'),
  'izle-ve-ayni-sirayla-tekrarla': require('../assets/sounds/tts/izle-ve-ayni-sirayla-tekrarla.wav'),
  'kac-nokta-var-say-bakalim': require('../assets/sounds/tts/kac-nokta-var-say-bakalim.wav'),
  'kac-tane-kaldi-say-bakalim': require('../assets/sounds/tts/kac-tane-kaldi-say-bakalim.wav'),
  'kac-tane-var-say-bakalim': require('../assets/sounds/tts/kac-tane-var-say-bakalim.wav'),
  'muhtesem-bir-mandala-aferin': require('../assets/sounds/tts/muhtesem-bir-mandala-aferin.wav'),
  'ne-degisti-degiseni-bul': require('../assets/sounds/tts/ne-degisti-degiseni-bul.wav'),
  'ne-guzel-bir-simetri-aferin': require('../assets/sounds/tts/ne-guzel-bir-simetri-aferin.wav'),
  'ne-guzel-cizdin-aferin': require('../assets/sounds/tts/ne-guzel-cizdin-aferin.wav'),
  'ne-guzel-noktalar-aferin': require('../assets/sounds/tts/ne-guzel-noktalar-aferin.wav'),
  'ne-guzel-susledin-aferin': require('../assets/sounds/tts/ne-guzel-susledin-aferin.wav'),
  'ne-komik-bir-yuz-aferin': require('../assets/sounds/tts/ne-komik-bir-yuz-aferin.wav'),
  'once-ne-olur-en-bastan-sirayla-dokun': require('../assets/sounds/tts/once-ne-olur-en-bastan-sirayla-dokun.wav'),
  'rengarenk-bir-kum-resmi-aferin': require('../assets/sounds/tts/rengarenk-bir-kum-resmi-aferin.wav'),
  'sirada-hangi-renk-var': require('../assets/sounds/tts/sirada-hangi-renk-var.wav'),
  'tebrikler': require('../assets/sounds/tts/tebrikler.wav'),
  'tekrar-dene': require('../assets/sounds/tts/tekrar-dene.wav'),
  'tekrar-izle-bakalim': require('../assets/sounds/tts/tekrar-izle-bakalim.wav'),
  'yasasin-peyniri-buldun-aferin': require('../assets/sounds/tts/yasasin-peyniri-buldun-aferin.wav'),
  'zit-olanlari-eslestir': require('../assets/sounds/tts/zit-olanlari-eslestir.wav'),
};
